/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:df321403-b48e-4dd1-ba71-5b3304590a8b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_gNw5AvXCM",
    "aws_user_pools_web_client_id": "5jtc3bhuskv9096cflenmo5q0e",
    "oauth": {}
};


export default awsmobile;
